name: Clippy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: format
        run: make format
        working-directory: module1
      - name: clippy
        run: make lint
        working-directory: module1
      - name: test
        run: make test
        working-directory: module1
      - name: release
        run: make release
        working-directory: module1
